### PR TITLE
assure the upload will work

### PR DESCRIPTION
**Pull request by Richardk2n**
I had issues uploading to pypi and wanted to prevent that.

### CODE REVIEW

**Comment by Richardk2n** [comment]
Would you like to have a look at this @haplo?

**Comment by haplo** [comment]
> Would you like to have a look at this @haplo?

Sure thing, I will take a look.

Can you share more details on what went wrong?

**Comment by Richardk2n** [comment]
When the Readme file is not correctly formatted pypi refuses the upload with a error message:
``HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/``
``The description failed to render in the default format of reStructuredText. See https://pypi.org/help/#description-content-type for more information.``
This regularly causes me commit stuff like this: 906a3dd6f60347724bccc4a015371d74b023a513
To prevent that I want to run a check beforehand.

**Comment by haplo** [comment]
@Richardk2n Let's also add [this pre-commit hook that validates rst files with the same linter as PyPI's](https://github.com/Lucas-C/pre-commit-hooks-markup).

**Comment by haplo** [comment]
> @Richardk2n Let's also add [this pre-commit hook that validates rst files with the same linter as PyPI's](https://github.com/Lucas-C/pre-commit-hooks-markup).

There is also [this rstcheck hook](https://github.com/myint/rstcheck#use-as-a-pre-commit-hook), that seems very comprehensive, but I don't know whether it's 100% compatible with PyPI's syntax.

**Comment by Richardk2n** [comment]
I put both checks in (one as a pre-commit check, one as a Github action check". While doing so I made two mistakes. One was caught by one of the checks, the other by the other. So, they are not perfect, but i think, they are good enough.

**Pull request merged**
