### PR TITLE
Rename to pylsp prefix

### PR DESCRIPTION
**Pull request by Richardk2n**

### CODE REVIEW

**Comment by Richardk2n** [comment]
What do you think of this @haplo (I am asking, because you seem to have more experience).
It will break old config files, but it will probably (help) fix issues like #7 and avoid confusion about potential causes for errors as in #9

**Comment by haplo** [comment]
Breaking changes would be bad for existing users, but good for new users. If we could find a way to ease the transition that would be best. An idea is to support multiple configuration namespaces (like `mypy-ls`, `mypy_ls`, `pylsp_mypy`), but deciding on one canonical one. Then try reading from the canonical one first, if not available try the other ones and raise a `DeprecationWarning` if any of those are found. That would hint existing users to update their configuration. The `DeprecationWarning` can be removed and an error raised instead in the future once everybody has had time to update.

About PyPI, I see you [already published *pylsp-mypy*](https://pypi.org/project/pylsp-mypy/). You should probably release [mypy-ls](https://pypi.org/project/mypy-ls/) with a big *DEPRECATED* warning on top telling users to switch to *pylsp-mypy*.

**Comment by Richardk2n** [comment]
I added deprecation warnings and intend to push an update to mypy-ls to depend on pylsp-mypy and contain nothing else, so existing users get upgraded automatically. What is left is renaming the GitHub repo and changing the link in setup.cfg

**Comment by rchl** [comment]
Did it actually address #7? I think it will still be the case that the setting for enabling will have to be called `pylsp-mypy.enabled` but other setting will have to be called `pylsp_mypy.*` (note the dash vs. underscore).

**Comment by rchl** [comment]
The setting for enabling is somehow automatically inferred by pylsp, I believe, and I'm not sure if it's even possible to change it (couldn't figure out after quick look at least). So changing the naming of `pylsp_mypy` settings might be an option instead.

**Comment by rchl** [comment]
No, sorry, looking at the diff it looks like this was actually addressed. It should use underscore consistently now. Thanks!

**Comment by Richardk2n** [comment]
> The setting for enabling is somehow automatically inferred by pylsp, I believe, and I'm not sure if it's even possible to change it (couldn't figure out after quick look at least). So changing the naming of `pylsp_mypy` settings might be an option instead.

I am assuming, the name is automatically inferred from either the package name which has an underscore or the entry point which also has an entry point, but i don't know to be honest.

**Pull request merged**
